
--------------------PACKAGE------------------------------------------------------------------------
--Cộng điểm thưởng khi mua hàng
CREATE OR REPLACE PACKAGE PKG_KHACHHANG AS
    FUNCTION TINH_DIEM(p_TONGTIEN NUMBER) RETURN NUMBER;
    PROCEDURE CAPNHAT_DIEM(p_MAKH VARCHAR2, p_TONGTIEN NUMBER);
END PKG_KHACHHANG;

CREATE OR REPLACE PACKAGE BODY PKG_KHACHHANG AS
    FUNCTION TINH_DIEM(p_TONGTIEN NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN FLOOR(p_TONGTIEN / 10000); -- Mỗi 10k được 1 điểm
    END;

    PROCEDURE CAPNHAT_DIEM(p_MAKH VARCHAR2, p_TONGTIEN NUMBER) IS
    BEGIN
        UPDATE KHACHHANG
        SET DIEMTL = DIEMTL + TINH_DIEM(p_TONGTIEN)
        WHERE MAKH = p_MAKH;
    END;
END PKG_KHACHHANG;

--Lệnh kiểm tra
-- Tính điểm với số tiền 253000
SELECT PKG_KHACHHANG.TINH_DIEM(253000) FROM DUAL; -- → 25 điểm

--cập nhật điểm
BEGIN
    PKG_KHACHHANG.CAPNHAT_DIEM('KH01', 120000);
END;


--Xem tat ca package dang ton tai
SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE';

