CREATE TABLESPACE DUYTB_QUANLYBANHANG DATAFILE '/opt/oracle/oradata/DUYTB_QUANLYBANHANG.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

ALTER USER duy_admin DEFAULT TABLESPACE DUYTB_QUANLYBANHANG QUOTA UNLIMITED ON DUYTB_QUANLYBANHANG;
SELECT USERNAME, DEFAULT_TABLESPACE FROM DBA_USERS WHERE USERNAME = 'DUY_ADMIN';

GRANT ALL PRIVILEGES TO duy_admin; --cấp mọi quyền cho user