CREATE ROLE SALE_ROLE;
CREATE ROLE WAREHOUSE_ROLE;
CREATE ROLE DRIVER_ROLE;
CREATE ROLE CUSTOMER_ROLE;
--SELECT role FROM dba_roles;
--SELECT role FROM dba_roles WHERE role = 'WAREHOUSE_ROLE';
--SELECT role FROM dba_roles WHERE role = 'DRIVER_ROLE';
--SELECT role FROM dba_roles WHERE role = 'CUSTOMER_ROLE';

--Đối với nhân viên bán hàng, ta có thể phân cho họ quyền thêm, xóa, sửa ở bảng khách hàng (KHACHAHNG), đơn giao đi (DON_DELIVERY), đơn ăn tại chỗ (DON_DINEIN):
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO SALE_ROLE;
GRANT SELECT, INSERT, UPDATE ON DON_DINEIN TO SALE_ROLE;
GRANT SELECT, INSERT, UPDATE ON DON_DELIVERY TO SALE_ROLE;
GRANT CREATE SESSION TO SALE_ROLE;

--Đối với nhân viên kho, họ sẽ có thêm, xóa, sửa ở bảng món ăn (MONAN)
GRANT SELECT, INSERT, UPDATE ON MONAN TO WAREHOUSE_ROLE;
GRANT CREATE SESSION TO WAREHOUSE_ROLE;

--Đối với tài xế, họ sẽ có quyền truy xuất các đơn giao đi (DON_DELIVERY):
GRANT SELECT ON DON_DELIVERY TO DRIVER_ROLE;
-- GRANT CREATE SESSION TO DRIVER_ROLE;

--Đối với khách hàng, họ sẽ có quyền truy xuất các món ăn (MONAN), khuyến mãi (VOUCHER)
GRANT SELECT ON MONAN TO CUSTOMER_ROLE;
GRANT SELECT ON VOUCHER TO CUSTOMER_ROLE;
-- GRANT CREATE SESSION TO CUSTOMER_ROLE;

SELECT *
FROM all_tab_privs
WHERE grantee = 'SALE_ROLE';

SELECT *
FROM all_tab_privs
WHERE grantee = 'WAREHOUSE_ROLE';

SELECT *
FROM all_tab_privs
WHERE grantee = 'DRIVER_ROLE';

SELECT *
FROM all_tab_privs
WHERE grantee = 'CUSTOMER_ROLE';

--Kiểm tra quyền của ROLE
SELECT *
FROM all_tab_privs
WHERE grantee IN ('SALE_ROLE', 'WAREHOUSE_ROLE', 'DRIVER_ROLE', 'CUSTOMER_ROLE');

--Tạo user cho từng ROLE:
CREATE USER SALE_USER IDENTIFIED BY sale123 DEFAULT TABLESPACE DUYTB_QUANLYBANHANG QUOTA UNLIMITED ON DUYTB_QUANLYBANHANG;
CREATE USER WAREHOUSE_USER IDENTIFIED BY warehouse123 DEFAULT TABLESPACE DUYTB_QUANLYBANHANG QUOTA UNLIMITED ON DUYTB_QUANLYBANHANG;
CREATE USER DRIVER_USER IDENTIFIED BY driver123 DEFAULT TABLESPACE DUYTB_QUANLYBANHANG QUOTA UNLIMITED ON DUYTB_QUANLYBANHANG;
CREATE USER CUSTOMER_USER IDENTIFIED BY customer123 DEFAULT TABLESPACE DUYTB_QUANLYBANHANG QUOTA UNLIMITED ON DUYTB_QUANLYBANHANG;

--Gan role cho tung user
GRANT SALE_ROLE TO SALE_USER;
GRANT WAREHOUSE_ROLE TO WAREHOUSE_USER;
GRANT DRIVER_ROLE TO DRIVER_USER;
GRANT CUSTOMER_ROLE TO CUSTOMER_USER;

--Kiểm tra user đang có role gì
SELECT *
FROM dba_role_privs
WHERE grantee = 'SALE_USER';

SELECT *
FROM dba_role_privs
WHERE grantee = 'WAREHOUSE_USER';

SELECT *
FROM dba_role_privs
WHERE grantee = 'DRIVER_USER';

SELECT *
FROM dba_role_privs
WHERE grantee = 'CUSTOMER_USER';
